# Generated by Django 3.2 on 2021-04-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210422_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='isbn_number',
            field=models.IntegerField(blank=True, default='17354', max_length=50, null=True, unique=True),
        ),
    ]
