# Generated by Django 3.2 on 2021-04-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_isbn_isbn_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='isbn',
            name='isbn_number',
            field=models.IntegerField(blank=True, default='42674', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.tag'),
        ),
    ]
