# Generated by Django 3.2 on 2021-04-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210422_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='isbn_number',
            field=models.IntegerField(blank=True, default='15034', max_length=50, null=True, unique=True),
        ),
    ]
