# Generated by Django 3.2 on 2021-04-23 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_isbn_isbn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='isbn_number',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=150, null=True, unique=True),
        ),
    ]
